[package]
name = "ecs_ui_sync"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
haalka = { path = "../../" }
bevy = "0.12.1"
bevy_rand = { version = "0.4.0", features = ["rand_chacha"] }
rand = "0.8.5"
