[workspace]
members = ["examples/*", "MoonZoon/crates/*"]
resolver = "2"

[package]
name = "haalka"
version = "0.1.1"
edition = "2021"
categories = ["asynchronous", "gui", "game-development"]
description = "ergonomic reactive Bevy UI library powered by FRP signals"
exclude = ["assets/", ".github/", "crates/"]
keywords = ["ui", "reactive", "signals", "gamedev", "bevy"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/databasedav/haalka"
documentation = "https://docs.rs/haalka"

[lints.rust]
missing_docs = "warn"
unsafe_code = "deny"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

# TODO: use MoonZoon's futures-signals/futures-util extensions directly when it is published as a crate
[dependencies]
apply = "0.3.0"
async-io = "2.3.1"
async-lock = "3.3.0"
bevy = "0.13.2"
bevy_cosmic_edit = { version = "0.20.1", optional = true }
bevy_eventlistener = "0.7.0"
bevy_mod_picking = { version = "0.19.0", default-features = false, features = ["backend_bevy_ui"], optional = true }
bevy-async-ecs = "0.5.0"
cfg-if = "1.0"
enclose = "1.1.8"
futures-signals = "0.3.33"
haalka_futures_signals_ext = { path = "MoonZoon/crates/futures_signals_ext", version = "0.0.1" }
once_cell = "1.19.0"
paste = { version = "1.0.14", optional = true }

[features]
default = [
    "text_input",
    "utils",
]
text_input = ["ui", "bevy_cosmic_edit"]
ui = ["bevy_mod_picking", "derive"]
derive = ["paste"]
utils = []

[dev-dependencies]
bevy_asset_loader = { version = "0.20.0", features = ["2d"] }
bevy_nine_slice_ui = "0.6.0"
bevy_rand = { version = "0.5.0", features = ["rand_chacha"] }
colorgrad = "0.6.2"
rand = "0.8.5"
strum = { version = "0.25.0", features = ["derive"] }
calc = { version = "0.4.0", default-features = false }
rust_decimal = "1.35"

[[example]]
name = "align"
path = "examples/align.rs"
doc-scrape-examples = true

[[example]]
name = "button"
path = "examples/button.rs"
doc-scrape-examples = true

[[example]]
name = "challenge01"
path = "examples/challenge01.rs"
doc-scrape-examples = true

[[example]]
name = "challenge02"
path = "examples/challenge02.rs"
doc-scrape-examples = true

[[example]]
name = "challenge03"
path = "examples/challenge03.rs"
doc-scrape-examples = true

[[example]]
name = "challenge04"
path = "examples/challenge04.rs"
doc-scrape-examples = true

[[example]]
name = "challenge05"
path = "examples/challenge05.rs"
doc-scrape-examples = true

[[example]]
name = "counter"
path = "examples/counter.rs"
doc-scrape-examples = true

[[example]]
name = "ecs_ui_sync"
path = "examples/ecs_ui_sync.rs"
doc-scrape-examples = true

[[example]]
name = "key_values_sorted"
path = "examples/key_values_sorted.rs"
doc-scrape-examples = true

[[example]]
name = "scroll_grid"
path = "examples/scroll_grid.rs"
doc-scrape-examples = true

[[example]]
name = "scroll"
path = "examples/scroll.rs"
doc-scrape-examples = true

[[example]]
name = "snake"
path = "examples/snake.rs"
doc-scrape-examples = true

[[example]]
name = "calculator"
path = "examples/calculator.rs"
doc-scrape-examples = true
