[package]
name = "haalka"
version = "0.1.0"
edition = "2021"

[dependencies]
async-io = "2.2.2"
bevy = "0.12.1"
bevy-async-ecs = "0.3.0"
enclose = "1.1.8"
futures-signals = "0.3.33"


[[example]]
name = "button"
