[workspace]
members = ["examples/*"]
resolver = "2"

[package]
name = "haalka"
version = "0.1.0"
edition = "2021"

[dependencies]
async-io = "2.2.2"
bevy = "0.12.1"
bevy-async-ecs = "0.3.0"
bevy_eventlistener = "0.6.1"
bevy_mod_picking = { version = "0.17.0", default-features = false, features = ["backend_bevy_ui", "selection"] }
enclose = "1.1.8"
futures-signals = "0.3.33"
futures-util = { version = "0.3.30", features = ["sink"] }  # TODO: need to add sink feature upstream
futures_signals_ext = { git = "https://github.com/MoonZoon/MoonZoon", rev = "4bf101bd5ace83281bf570cc6fb601d1ad608a75" }
# syn = { version = "1.0", features = ["full", "parsing"] }  # TODO: need to add parsing, full features upstream + update syn version
static_ref_macro = { git = "https://github.com/databasedav/MoonZoon", rev = "004d03dee8ee487d53dffcd399f747ee3e9a4a95" }
paste = "1.0.14"
apply = "0.3.0"
