[workspace]
changelog_update = false
git_release_type = "auto"
git_release_draft = true

[[package]]
name = "haalka"
git_tag_name = "v{{ version }}"

[[package]]
name = "haalka_futures_signals_ext"
git_tag_enable = false

[[package]]
name = "haalka_futures_signals_ext"
git_tag_enable = false
