# from bevy
use_field_init_shorthand = true
newline_style = "Unix"

# requires nightly
unstable_features = true
trailing_comma = "Vertical"
max_width = 120
# from bevy
imports_granularity = "Crate"
wrap_comments = true
comment_width = 100
normalize_comments = true
