[package]
name = "challenge02"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
haalka = { path = "../../" }
bevy = "0.12.1"
bevy_asset_loader = { version = "0.19.1", features = ["2d"] }
rand = "0.8.5"
