[package]
name = "challenge05"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
haalka = { path = "../../" }
bevy = "0.13.1"
strum = { version = "0.26.1", features = ["derive"] }
bevy_cosmic_edit = "0.16.0"
