[package]
name = "challenge05"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
haalka = { path = "../../" }
bevy = "0.12.1"
bevy_simple_text_input = "0.3.1"
strum = { version = "0.26.1", features = ["derive"] }
