[package]
name = "snake"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
haalka = { path = "../../" }
bevy = "0.13.2"
rand = "0.8.5"
bevy_rand = { version = "0.5.0", features = ["rand_chacha"] }
strum = { version = "0.25.0", features = ["derive"] }
